typeset -U path

if [[ -d /opt/local/lib/ImageMagick7/bin ]]; then
  path=(/opt/local/lib/ImageMagick7/bin $path)
fi
if [[ -d /opt/local/bin ]]; then
  path=(/opt/local/bin $path)
fi
if [[ -d /opt/local/sbin ]]; then
  path=(/opt/local/sbin $path)
fi
if [[ -d $HOME/.local/bin ]]; then
  path=($HOME/.local/bin $path)
fi
