typeset -U path

export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

if [[ -d /opt/local/lib/ImageMagick7/bin ]]; then
  path=(/opt/local/lib/ImageMagick7/bin $path)
fi
if [[ -d /opt/local/bin ]]; then
  path=(/opt/local/bin $path)
fi
if [[ -d /opt/local/sbin ]]; then
  path=(/opt/local/sbin $path)
fi
if [[ -d $HOME/.local/bin ]]; then
  path=($HOME/.local/bin $path)
fi
